env:
  global:
    - CC_TEST_REPORTER_ID=7bee48f8a6b81501d9ac7d0f45517d7721c15fe1b09a6d23d3928bb05c122b90
language: ruby
rvm:
  - 2.3.1
sudo: required
before_install: # if "install" is overridden
# Repo for Yarn
- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt-get update -qq
- sudo apt-get install -y -qq yarn
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn install
  - RAILS_ENV=test bundle exec rails db:migrate --trace
  - bundle exec rails db:test:prepare
  - RAILS_ENV=test bundle exec rails assets:precompile
  - RAILS_ENV=test bundle exec rspec
  - RAILS_ENV=test bundle exec cucumber
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT