Feature: Student select map event after iteration pull from events in a drop down
  As a student
  So I will see task graph generated by staff
  I will be able to map task to specific type event through drop down according to my type dynamically

  Background: I have a task graph and new event just came in
    Given I am logged in as student
    And I am under "map task iteration" with the following tasks:
      | title       | updater_type | update_status |
      | githubTask  | github       | started       |
      | pivotalTask | pivotal      | started       |
      | localTask   | local        | started       |
      | githubTask1 | github       | finished      |
      | pivotalTask1| pivotal      | finished      |
      | localTask1  | local        | finished      |
      | githubTask2 | github       | danger        |
      | pivotalTask2| pivotal      | danger        |
      | localTask2  | local        | danger        |

    Then I send update request to events and receive "event_call_back"

  Scenario: I will iterate though the tasks and events and map them
    

  Scenario: I will update the tasks if they reach the requirement